language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t davegimo/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true davegimo/docker-react npm run test